#!/bin/sh

sudo docker build --no-cache --tag bahnk/scvidowngrade:v1 .
sudo docker image tag bahnk/scvi:v1 bahnk/scvidowngrade:v1
sudo docker login -u bahnk docker.io
sudo docker push bahnk/scvidowngrade:v1

module load Singularity/3.6.4
singularity pull --disable-cache scvidowngrade.sif docker://bahnk/scvidowngrade:v1

