#!/bin/sh

sudo docker build --no-cache --tag bahnk/seqgpu:v1 .
sudo docker login -u "bahnk" docker.io
sudo docker push bahnk/seqgpu:v1

module load Singularity/3.6.4
singularity pull --disable-cache seqgpu.sif docker://bahnk/seqgpu:v1

