#!/bin/sh

sudo docker build --no-cache --tag sequencing:v2 .
sudo docker image tag sequencing:v1 bahnk/sequencing:v2
sudo docker login -u "bahnk" -p "" docker.io
sudo docker push bahnk/sequencing:v2

