#!/bin/sh

sudo docker build --no-cache --tag bahnk/quarto:v1 .
sudo docker login -u "bahnk" docker.io
sudo docker push bahnk/quarto:v1

module load Singularity/3.6.4
singularity pull --disable-cache quarto.sif docker://bahnk/quarto:v1

