#!/bin/sh

sudo docker build --tag bahnk/python:v2 .
sudo docker build --no-cache --tag bahnk/python:v2 .
sudo docker login -u "bahnk" -p "" docker.io
sudo docker push bahnk/python:v2
singularity pull python.sif docker://bahnk/python:v2
