#!/bin/sh

sudo docker build --no-cache --tag bahnk/r:v1 v1
sudo docker login -u "bahnk" docker.io
sudo docker push bahnk/r:v1

module load Singularity/3.6.4
singularity pull --disable-cache general.sif docker://bahnk/r:v1

